name: PetTransportation
version: ${project.version}
author: jjm_223
description: Allows you to throw an egg at a pet (wolf or ocelot) to keep it in your inventory.
main: me.jjm_223.pt.PetTransportation